package RollCall.RollCall.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "shifts") // Maps this class to the "shifts" table in the database
public class ShiftModel {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Auto-generated primary key
    @Column(name = "shift_id", nullable = false, unique = true)
    private Long shiftId;

    @ManyToOne // Many shifts can belong to one user
    @JoinColumn(name = "userid", nullable = false, foreignKey = @ForeignKey(name = "shifts_userid_fk"))
    private UserModel userModel; // Reference to the UserModel entity

    //
    @Column(name = "start_time_stamp") // Maps to the "start_time_stamp" column
    private LocalDateTime startTimeStamp;

    @Column(name = "end_time_stamp") // Maps to the "end_time_stamp" column
    private LocalDateTime endTimeStamp;

    // Getters and Setters

    public Long getShiftId() {
        return shiftId;
    }
    // No setShiftId because this field is auto-generated by the database

    public UserModel getUserModel() {
        return userModel;
    }
    public void setUserModel(UserModel userModel) {
        this.userModel = userModel;
    }

    public LocalDateTime getStartTimeStamp() {
        return startTimeStamp;
    }
    public void setStartTimeStamp(LocalDateTime startTimeStamp) {
        this.startTimeStamp = startTimeStamp;
    }

    public LocalDateTime getEndTimeStamp() {
        return endTimeStamp;
    }
    public void setEndTimeStamp(LocalDateTime endTimeStamp) {
        this.endTimeStamp = endTimeStamp;
    }
}

/*
 * ShiftModel:
 * - Represents a work shift in the "shifts" table.
 * - Each shift is associated with a user (via a Many-to-One relationship).
 * - The start and end timestamps track when the shift began and ended.
 */
